language: node_js
sudo: false
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success: 'npm run coveralls'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
